#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCIP.FLM
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="AMS.2009.12.23")]
	public partial class AMS_DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public AMS_DataClassesDataContext() : 
				base(global::DCIP.FLM.Properties.Settings.Default.AMS_2009_12_23ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AMS_DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AMS_DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AMS_DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AMS_DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[Function(Name="dbo.flm_GetFacilitySecureEquipment")]
		public ISingleResult<flm_GetFacilitySecureEquipmentResult> flm_GetFacilitySecureEquipment([Parameter(Name="Site_Id", DbType="Int")] System.Nullable<int> site_Id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), site_Id);
			return ((ISingleResult<flm_GetFacilitySecureEquipmentResult>)(result.ReturnValue));
		}
		
		[Function(Name="dbo.flm_GetNonCriticalAuditoriumInfo")]
		public ISingleResult<flm_GetNonCriticalAuditoriumInfoResult> flm_GetNonCriticalAuditoriumInfo([Parameter(Name="Site_Id", DbType="Int")] System.Nullable<int> site_Id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), site_Id);
			return ((ISingleResult<flm_GetNonCriticalAuditoriumInfoResult>)(result.ReturnValue));
		}
		
		[Function(Name="dbo.flm_GetFacilityDeviceList")]
		public ISingleResult<flm_GetFacilityDeviceListResult> flm_GetFacilityDeviceList([Parameter(Name="Site_Id", DbType="Int")] System.Nullable<int> site_Id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), site_Id);
			return ((ISingleResult<flm_GetFacilityDeviceListResult>)(result.ReturnValue));
		}
		
		[Function(Name="dbo.flm_GetFacilityInfo")]
		public ISingleResult<flm_GetFacilityInfoResult> flm_GetFacilityInfo([Parameter(Name="Site_Id", DbType="Int")] System.Nullable<int> site_Id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), site_Id);
			return ((ISingleResult<flm_GetFacilityInfoResult>)(result.ReturnValue));
		}
		
		[Function(Name="dbo.flm_GetNonCriticalFacilityInfo")]
		public ISingleResult<flm_GetNonCriticalFacilityInfoResult> flm_GetNonCriticalFacilityInfo([Parameter(Name="Site_Id", DbType="Int")] System.Nullable<int> site_Id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), site_Id);
			return ((ISingleResult<flm_GetNonCriticalFacilityInfoResult>)(result.ReturnValue));
		}
	}
	
	public partial class flm_GetFacilitySecureEquipmentResult
	{
		
		private int _Site_Id;
		
		private int _Location_Id;
		
		private int _Location_Type_Id;
		
		private string _Location_Type_Name;
		
		private System.Nullable<int> _Auditorium_Code;
		
		private System.Nullable<int> _Equipment_Id;
		
		private string _Name;
		
		private string _Description;
		
		private string _Manufacturer;
		
		private System.Nullable<System.Guid> _Manufacturer_UniqueIdentifier;
		
		private string _Model;
		
		private string _Serial_Number;
		
		private System.Nullable<System.Guid> _UniqueIdentifier;
		
		private string _Cert_String;
		
		private string _FLM_DeviceType;
		
		private string _Attribute_Value;
		
		private string _Equipment_Attribute_Datatype;
		
		private string _Equipment_Attribute_Name;
		
		private System.Nullable<int> _Core_Attribute_Id;
		
		public flm_GetFacilitySecureEquipmentResult()
		{
		}
		
		[Column(Storage="_Site_Id", DbType="Int NOT NULL")]
		public int Site_Id
		{
			get
			{
				return this._Site_Id;
			}
			set
			{
				if ((this._Site_Id != value))
				{
					this._Site_Id = value;
				}
			}
		}
		
		[Column(Storage="_Location_Id", DbType="Int NOT NULL")]
		public int Location_Id
		{
			get
			{
				return this._Location_Id;
			}
			set
			{
				if ((this._Location_Id != value))
				{
					this._Location_Id = value;
				}
			}
		}
		
		[Column(Storage="_Location_Type_Id", DbType="Int NOT NULL")]
		public int Location_Type_Id
		{
			get
			{
				return this._Location_Type_Id;
			}
			set
			{
				if ((this._Location_Type_Id != value))
				{
					this._Location_Type_Id = value;
				}
			}
		}
		
		[Column(Storage="_Location_Type_Name", DbType="VarChar(50)")]
		public string Location_Type_Name
		{
			get
			{
				return this._Location_Type_Name;
			}
			set
			{
				if ((this._Location_Type_Name != value))
				{
					this._Location_Type_Name = value;
				}
			}
		}
		
		[Column(Storage="_Auditorium_Code", DbType="Int")]
		public System.Nullable<int> Auditorium_Code
		{
			get
			{
				return this._Auditorium_Code;
			}
			set
			{
				if ((this._Auditorium_Code != value))
				{
					this._Auditorium_Code = value;
				}
			}
		}
		
		[Column(Storage="_Equipment_Id", DbType="Int")]
		public System.Nullable<int> Equipment_Id
		{
			get
			{
				return this._Equipment_Id;
			}
			set
			{
				if ((this._Equipment_Id != value))
				{
					this._Equipment_Id = value;
				}
			}
		}
		
		[Column(Storage="_Name", DbType="VarChar(64)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[Column(Storage="_Description", DbType="VarChar(128)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[Column(Storage="_Manufacturer", DbType="VarChar(64)")]
		public string Manufacturer
		{
			get
			{
				return this._Manufacturer;
			}
			set
			{
				if ((this._Manufacturer != value))
				{
					this._Manufacturer = value;
				}
			}
		}
		
		[Column(Storage="_Manufacturer_UniqueIdentifier", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> Manufacturer_UniqueIdentifier
		{
			get
			{
				return this._Manufacturer_UniqueIdentifier;
			}
			set
			{
				if ((this._Manufacturer_UniqueIdentifier != value))
				{
					this._Manufacturer_UniqueIdentifier = value;
				}
			}
		}
		
		[Column(Storage="_Model", DbType="VarChar(32)")]
		public string Model
		{
			get
			{
				return this._Model;
			}
			set
			{
				if ((this._Model != value))
				{
					this._Model = value;
				}
			}
		}
		
		[Column(Storage="_Serial_Number", DbType="VarChar(50)")]
		public string Serial_Number
		{
			get
			{
				return this._Serial_Number;
			}
			set
			{
				if ((this._Serial_Number != value))
				{
					this._Serial_Number = value;
				}
			}
		}
		
		[Column(Storage="_UniqueIdentifier", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> UniqueIdentifier
		{
			get
			{
				return this._UniqueIdentifier;
			}
			set
			{
				if ((this._UniqueIdentifier != value))
				{
					this._UniqueIdentifier = value;
				}
			}
		}
		
		[Column(Storage="_Cert_String", DbType="VarChar(8000)")]
		public string Cert_String
		{
			get
			{
				return this._Cert_String;
			}
			set
			{
				if ((this._Cert_String != value))
				{
					this._Cert_String = value;
				}
			}
		}
		
		[Column(Storage="_FLM_DeviceType", DbType="VarChar(50)")]
		public string FLM_DeviceType
		{
			get
			{
				return this._FLM_DeviceType;
			}
			set
			{
				if ((this._FLM_DeviceType != value))
				{
					this._FLM_DeviceType = value;
				}
			}
		}
		
		[Column(Storage="_Attribute_Value", DbType="VarChar(128)")]
		public string Attribute_Value
		{
			get
			{
				return this._Attribute_Value;
			}
			set
			{
				if ((this._Attribute_Value != value))
				{
					this._Attribute_Value = value;
				}
			}
		}
		
		[Column(Storage="_Equipment_Attribute_Datatype", DbType="VarChar(50)")]
		public string Equipment_Attribute_Datatype
		{
			get
			{
				return this._Equipment_Attribute_Datatype;
			}
			set
			{
				if ((this._Equipment_Attribute_Datatype != value))
				{
					this._Equipment_Attribute_Datatype = value;
				}
			}
		}
		
		[Column(Storage="_Equipment_Attribute_Name", DbType="VarChar(50)")]
		public string Equipment_Attribute_Name
		{
			get
			{
				return this._Equipment_Attribute_Name;
			}
			set
			{
				if ((this._Equipment_Attribute_Name != value))
				{
					this._Equipment_Attribute_Name = value;
				}
			}
		}
		
		[Column(Storage="_Core_Attribute_Id", DbType="Int")]
		public System.Nullable<int> Core_Attribute_Id
		{
			get
			{
				return this._Core_Attribute_Id;
			}
			set
			{
				if ((this._Core_Attribute_Id != value))
				{
					this._Core_Attribute_Id = value;
				}
			}
		}
	}
	
	public partial class flm_GetNonCriticalAuditoriumInfoResult
	{
		
		private int _Site_Id;
		
		private System.Nullable<int> _Auditorium_Id;
		
		private System.Nullable<bool> _Auditorium_3D;
		
		private System.Nullable<int> _Auditorium_Code;
		
		private System.Nullable<System.DateTime> _Acceptance_Date;
		
		private System.Nullable<bool> _Silver_Screen;
		
		private string _Type_Description;
		
		private System.Nullable<System.DateTime> _Date_Standard_Conversion;
		
		private System.Nullable<System.DateTime> _Date_3D_Conversion;
		
		private System.Nullable<bool> _Auditorium_IMAX;
		
		private System.Nullable<bool> _Conversion;
		
		public flm_GetNonCriticalAuditoriumInfoResult()
		{
		}
		
		[Column(Storage="_Site_Id", DbType="Int NOT NULL")]
		public int Site_Id
		{
			get
			{
				return this._Site_Id;
			}
			set
			{
				if ((this._Site_Id != value))
				{
					this._Site_Id = value;
				}
			}
		}
		
		[Column(Storage="_Auditorium_Id", DbType="Int")]
		public System.Nullable<int> Auditorium_Id
		{
			get
			{
				return this._Auditorium_Id;
			}
			set
			{
				if ((this._Auditorium_Id != value))
				{
					this._Auditorium_Id = value;
				}
			}
		}
		
		[Column(Storage="_Auditorium_3D", DbType="Bit")]
		public System.Nullable<bool> Auditorium_3D
		{
			get
			{
				return this._Auditorium_3D;
			}
			set
			{
				if ((this._Auditorium_3D != value))
				{
					this._Auditorium_3D = value;
				}
			}
		}
		
		[Column(Storage="_Auditorium_Code", DbType="Int")]
		public System.Nullable<int> Auditorium_Code
		{
			get
			{
				return this._Auditorium_Code;
			}
			set
			{
				if ((this._Auditorium_Code != value))
				{
					this._Auditorium_Code = value;
				}
			}
		}
		
		[Column(Storage="_Acceptance_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Acceptance_Date
		{
			get
			{
				return this._Acceptance_Date;
			}
			set
			{
				if ((this._Acceptance_Date != value))
				{
					this._Acceptance_Date = value;
				}
			}
		}
		
		[Column(Storage="_Silver_Screen", DbType="Bit")]
		public System.Nullable<bool> Silver_Screen
		{
			get
			{
				return this._Silver_Screen;
			}
			set
			{
				if ((this._Silver_Screen != value))
				{
					this._Silver_Screen = value;
				}
			}
		}
		
		[Column(Storage="_Type_Description", DbType="VarChar(128)")]
		public string Type_Description
		{
			get
			{
				return this._Type_Description;
			}
			set
			{
				if ((this._Type_Description != value))
				{
					this._Type_Description = value;
				}
			}
		}
		
		[Column(Storage="_Date_Standard_Conversion", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date_Standard_Conversion
		{
			get
			{
				return this._Date_Standard_Conversion;
			}
			set
			{
				if ((this._Date_Standard_Conversion != value))
				{
					this._Date_Standard_Conversion = value;
				}
			}
		}
		
		[Column(Storage="_Date_3D_Conversion", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date_3D_Conversion
		{
			get
			{
				return this._Date_3D_Conversion;
			}
			set
			{
				if ((this._Date_3D_Conversion != value))
				{
					this._Date_3D_Conversion = value;
				}
			}
		}
		
		[Column(Storage="_Auditorium_IMAX", DbType="Bit")]
		public System.Nullable<bool> Auditorium_IMAX
		{
			get
			{
				return this._Auditorium_IMAX;
			}
			set
			{
				if ((this._Auditorium_IMAX != value))
				{
					this._Auditorium_IMAX = value;
				}
			}
		}
		
		[Column(Storage="_Conversion", DbType="Bit")]
		public System.Nullable<bool> Conversion
		{
			get
			{
				return this._Conversion;
			}
			set
			{
				if ((this._Conversion != value))
				{
					this._Conversion = value;
				}
			}
		}
	}
	
	public partial class flm_GetFacilityDeviceListResult
	{
		
		private int _Site_Id;
		
		private System.Nullable<System.DateTime> _Acceptance_Date;
		
		private int _Location_Id;
		
		private int _Location_Type_Id;
		
		private string _Location_Type_Name;
		
		private System.Nullable<int> _Auditorium_Code;
		
		private System.Nullable<int> _Equipment_Id;
		
		private string _Name;
		
		private string _Description;
		
		private string _Manufacturer;
		
		private System.Nullable<System.Guid> _Manufacturer_UniqueIdentifier;
		
		private string _Model;
		
		private string _Serial_Number;
		
		private string _Cert_String;
		
		private string _FLM_DeviceType;
		
		private string _Attribute_Value;
		
		private string _Equipment_Attribute_Datatype;
		
		private string _Equipment_Attribute_Name;
		
		private System.Nullable<int> _Core_Attribute_Id;
		
		private System.Nullable<System.DateTime> _Installed_Date;
		
		private System.Nullable<System.DateTime> _Decommission_Date;
		
		public flm_GetFacilityDeviceListResult()
		{
		}
		
		[Column(Storage="_Site_Id", DbType="Int NOT NULL")]
		public int Site_Id
		{
			get
			{
				return this._Site_Id;
			}
			set
			{
				if ((this._Site_Id != value))
				{
					this._Site_Id = value;
				}
			}
		}
		
		[Column(Storage="_Acceptance_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Acceptance_Date
		{
			get
			{
				return this._Acceptance_Date;
			}
			set
			{
				if ((this._Acceptance_Date != value))
				{
					this._Acceptance_Date = value;
				}
			}
		}
		
		[Column(Storage="_Location_Id", DbType="Int NOT NULL")]
		public int Location_Id
		{
			get
			{
				return this._Location_Id;
			}
			set
			{
				if ((this._Location_Id != value))
				{
					this._Location_Id = value;
				}
			}
		}
		
		[Column(Storage="_Location_Type_Id", DbType="Int NOT NULL")]
		public int Location_Type_Id
		{
			get
			{
				return this._Location_Type_Id;
			}
			set
			{
				if ((this._Location_Type_Id != value))
				{
					this._Location_Type_Id = value;
				}
			}
		}
		
		[Column(Storage="_Location_Type_Name", DbType="VarChar(50)")]
		public string Location_Type_Name
		{
			get
			{
				return this._Location_Type_Name;
			}
			set
			{
				if ((this._Location_Type_Name != value))
				{
					this._Location_Type_Name = value;
				}
			}
		}
		
		[Column(Storage="_Auditorium_Code", DbType="Int")]
		public System.Nullable<int> Auditorium_Code
		{
			get
			{
				return this._Auditorium_Code;
			}
			set
			{
				if ((this._Auditorium_Code != value))
				{
					this._Auditorium_Code = value;
				}
			}
		}
		
		[Column(Storage="_Equipment_Id", DbType="Int")]
		public System.Nullable<int> Equipment_Id
		{
			get
			{
				return this._Equipment_Id;
			}
			set
			{
				if ((this._Equipment_Id != value))
				{
					this._Equipment_Id = value;
				}
			}
		}
		
		[Column(Storage="_Name", DbType="VarChar(64)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[Column(Storage="_Description", DbType="VarChar(128)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[Column(Storage="_Manufacturer", DbType="VarChar(64)")]
		public string Manufacturer
		{
			get
			{
				return this._Manufacturer;
			}
			set
			{
				if ((this._Manufacturer != value))
				{
					this._Manufacturer = value;
				}
			}
		}
		
		[Column(Storage="_Manufacturer_UniqueIdentifier", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> Manufacturer_UniqueIdentifier
		{
			get
			{
				return this._Manufacturer_UniqueIdentifier;
			}
			set
			{
				if ((this._Manufacturer_UniqueIdentifier != value))
				{
					this._Manufacturer_UniqueIdentifier = value;
				}
			}
		}
		
		[Column(Storage="_Model", DbType="VarChar(32)")]
		public string Model
		{
			get
			{
				return this._Model;
			}
			set
			{
				if ((this._Model != value))
				{
					this._Model = value;
				}
			}
		}
		
		[Column(Storage="_Serial_Number", DbType="VarChar(50)")]
		public string Serial_Number
		{
			get
			{
				return this._Serial_Number;
			}
			set
			{
				if ((this._Serial_Number != value))
				{
					this._Serial_Number = value;
				}
			}
		}
		
		[Column(Storage="_Cert_String", DbType="VarChar(8000)")]
		public string Cert_String
		{
			get
			{
				return this._Cert_String;
			}
			set
			{
				if ((this._Cert_String != value))
				{
					this._Cert_String = value;
				}
			}
		}
		
		[Column(Storage="_FLM_DeviceType", DbType="VarChar(50)")]
		public string FLM_DeviceType
		{
			get
			{
				return this._FLM_DeviceType;
			}
			set
			{
				if ((this._FLM_DeviceType != value))
				{
					this._FLM_DeviceType = value;
				}
			}
		}
		
		[Column(Storage="_Attribute_Value", DbType="VarChar(128)")]
		public string Attribute_Value
		{
			get
			{
				return this._Attribute_Value;
			}
			set
			{
				if ((this._Attribute_Value != value))
				{
					this._Attribute_Value = value;
				}
			}
		}
		
		[Column(Storage="_Equipment_Attribute_Datatype", DbType="VarChar(50)")]
		public string Equipment_Attribute_Datatype
		{
			get
			{
				return this._Equipment_Attribute_Datatype;
			}
			set
			{
				if ((this._Equipment_Attribute_Datatype != value))
				{
					this._Equipment_Attribute_Datatype = value;
				}
			}
		}
		
		[Column(Storage="_Equipment_Attribute_Name", DbType="VarChar(50)")]
		public string Equipment_Attribute_Name
		{
			get
			{
				return this._Equipment_Attribute_Name;
			}
			set
			{
				if ((this._Equipment_Attribute_Name != value))
				{
					this._Equipment_Attribute_Name = value;
				}
			}
		}
		
		[Column(Storage="_Core_Attribute_Id", DbType="Int")]
		public System.Nullable<int> Core_Attribute_Id
		{
			get
			{
				return this._Core_Attribute_Id;
			}
			set
			{
				if ((this._Core_Attribute_Id != value))
				{
					this._Core_Attribute_Id = value;
				}
			}
		}
		
		[Column(Storage="_Installed_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Installed_Date
		{
			get
			{
				return this._Installed_Date;
			}
			set
			{
				if ((this._Installed_Date != value))
				{
					this._Installed_Date = value;
				}
			}
		}
		
		[Column(Storage="_Decommission_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Decommission_Date
		{
			get
			{
				return this._Decommission_Date;
			}
			set
			{
				if ((this._Decommission_Date != value))
				{
					this._Decommission_Date = value;
				}
			}
		}
	}
	
	public partial class flm_GetFacilityInfoResult
	{
		
		private string _Exhibitor_Name;
		
		private string _URI_Mapping;
		
		private int _Site_Id;
		
		private int _Site_Code;
		
		private string _Site_Name;
		
		private string _Alternate_Identifier;
		
		private string _Authoritative_Source_Name;
		
		public flm_GetFacilityInfoResult()
		{
		}
		
		[Column(Storage="_Exhibitor_Name", DbType="VarChar(256) NOT NULL", CanBeNull=false)]
		public string Exhibitor_Name
		{
			get
			{
				return this._Exhibitor_Name;
			}
			set
			{
				if ((this._Exhibitor_Name != value))
				{
					this._Exhibitor_Name = value;
				}
			}
		}
		
		[Column(Storage="_URI_Mapping", DbType="VarChar(50)")]
		public string URI_Mapping
		{
			get
			{
				return this._URI_Mapping;
			}
			set
			{
				if ((this._URI_Mapping != value))
				{
					this._URI_Mapping = value;
				}
			}
		}
		
		[Column(Storage="_Site_Id", DbType="Int NOT NULL")]
		public int Site_Id
		{
			get
			{
				return this._Site_Id;
			}
			set
			{
				if ((this._Site_Id != value))
				{
					this._Site_Id = value;
				}
			}
		}
		
		[Column(Storage="_Site_Code", DbType="Int NOT NULL")]
		public int Site_Code
		{
			get
			{
				return this._Site_Code;
			}
			set
			{
				if ((this._Site_Code != value))
				{
					this._Site_Code = value;
				}
			}
		}
		
		[Column(Storage="_Site_Name", DbType="VarChar(256) NOT NULL", CanBeNull=false)]
		public string Site_Name
		{
			get
			{
				return this._Site_Name;
			}
			set
			{
				if ((this._Site_Name != value))
				{
					this._Site_Name = value;
				}
			}
		}
		
		[Column(Storage="_Alternate_Identifier", DbType="VarChar(64) NOT NULL", CanBeNull=false)]
		public string Alternate_Identifier
		{
			get
			{
				return this._Alternate_Identifier;
			}
			set
			{
				if ((this._Alternate_Identifier != value))
				{
					this._Alternate_Identifier = value;
				}
			}
		}
		
		[Column(Storage="_Authoritative_Source_Name", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string Authoritative_Source_Name
		{
			get
			{
				return this._Authoritative_Source_Name;
			}
			set
			{
				if ((this._Authoritative_Source_Name != value))
				{
					this._Authoritative_Source_Name = value;
				}
			}
		}
	}
	
	public partial class flm_GetNonCriticalFacilityInfoResult
	{
		
		private string _Exhibitor_Name;
		
		private string _Street_1;
		
		private string _Street_2;
		
		private string _Street_3;
		
		private string _State;
		
		private string _City;
		
		private string _Zip_Code;
		
		private string _Nation;
		
		private string _Site_Name;
		
		private int _Site_Id;
		
		private System.Nullable<int> _TotalScreenCount;
		
		private string _Alternate_Identifier;
		
		private string _Authoritative_Source_Name;
		
		public flm_GetNonCriticalFacilityInfoResult()
		{
		}
		
		[Column(Storage="_Exhibitor_Name", DbType="VarChar(256) NOT NULL", CanBeNull=false)]
		public string Exhibitor_Name
		{
			get
			{
				return this._Exhibitor_Name;
			}
			set
			{
				if ((this._Exhibitor_Name != value))
				{
					this._Exhibitor_Name = value;
				}
			}
		}
		
		[Column(Storage="_Street_1", DbType="VarChar(64)")]
		public string Street_1
		{
			get
			{
				return this._Street_1;
			}
			set
			{
				if ((this._Street_1 != value))
				{
					this._Street_1 = value;
				}
			}
		}
		
		[Column(Storage="_Street_2", DbType="VarChar(64)")]
		public string Street_2
		{
			get
			{
				return this._Street_2;
			}
			set
			{
				if ((this._Street_2 != value))
				{
					this._Street_2 = value;
				}
			}
		}
		
		[Column(Storage="_Street_3", DbType="VarChar(64)")]
		public string Street_3
		{
			get
			{
				return this._Street_3;
			}
			set
			{
				if ((this._Street_3 != value))
				{
					this._Street_3 = value;
				}
			}
		}
		
		[Column(Storage="_State", DbType="VarChar(2)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this._State = value;
				}
			}
		}
		
		[Column(Storage="_City", DbType="VarChar(64)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[Column(Storage="_Zip_Code", DbType="NVarChar(16)")]
		public string Zip_Code
		{
			get
			{
				return this._Zip_Code;
			}
			set
			{
				if ((this._Zip_Code != value))
				{
					this._Zip_Code = value;
				}
			}
		}
		
		[Column(Storage="_Nation", DbType="VarChar(64)")]
		public string Nation
		{
			get
			{
				return this._Nation;
			}
			set
			{
				if ((this._Nation != value))
				{
					this._Nation = value;
				}
			}
		}
		
		[Column(Storage="_Site_Name", DbType="VarChar(256) NOT NULL", CanBeNull=false)]
		public string Site_Name
		{
			get
			{
				return this._Site_Name;
			}
			set
			{
				if ((this._Site_Name != value))
				{
					this._Site_Name = value;
				}
			}
		}
		
		[Column(Storage="_Site_Id", DbType="Int NOT NULL")]
		public int Site_Id
		{
			get
			{
				return this._Site_Id;
			}
			set
			{
				if ((this._Site_Id != value))
				{
					this._Site_Id = value;
				}
			}
		}
		
		[Column(Storage="_TotalScreenCount", DbType="Int")]
		public System.Nullable<int> TotalScreenCount
		{
			get
			{
				return this._TotalScreenCount;
			}
			set
			{
				if ((this._TotalScreenCount != value))
				{
					this._TotalScreenCount = value;
				}
			}
		}
		
		[Column(Storage="_Alternate_Identifier", DbType="VarChar(64) NOT NULL", CanBeNull=false)]
		public string Alternate_Identifier
		{
			get
			{
				return this._Alternate_Identifier;
			}
			set
			{
				if ((this._Alternate_Identifier != value))
				{
					this._Alternate_Identifier = value;
				}
			}
		}
		
		[Column(Storage="_Authoritative_Source_Name", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string Authoritative_Source_Name
		{
			get
			{
				return this._Authoritative_Source_Name;
			}
			set
			{
				if ((this._Authoritative_Source_Name != value))
				{
					this._Authoritative_Source_Name = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
