//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace www.smpte.org.etm
{
    using System.Xml.Serialization;
    using System.Security.Cryptography.Xml;
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.smpte-ra.org/schemas/430-3/2006/ETM")]
    [System.Xml.Serialization.XmlRootAttribute("DCinemaSecurityMessage", Namespace="http://www.smpte-ra.org/schemas/430-3/2006/ETM", IsNullable=false)]
    public partial class DCinemaSecurityMessageType {
        
        private AuthenticatedPublicType authenticatedPublicField;
        
        private AuthenticatedPrivateType authenticatedPrivateField;
        
        private System.Xml.XmlElement signatureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AuthenticatedPublicType AuthenticatedPublic {
            get {
                return this.authenticatedPublicField;
            }
            set {
                this.authenticatedPublicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public AuthenticatedPrivateType AuthenticatedPrivate {
            get {
                return this.authenticatedPrivateField;
            }
            set {
                this.authenticatedPrivateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.Xml.XmlElement Signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.smpte-ra.org/schemas/430-3/2006/ETM")]
    public partial class AuthenticatedPublicType {
        
        private string messageIdField;
        
        private string messageTypeField;
        
        private UserText annotationTextField;
        
        private System.DateTime issueDateField;
        
        //private System.Xml.XmlElement signerField;
        private X509IssuerSerial signerField;
        
        private System.Xml.XmlElement requiredExtensionsField;
        
        private System.Xml.XmlElement nonCriticalExtensionsField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=0)]
        public string MessageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=1)]
        public string MessageType {
            get {
                return this.messageTypeField;
            }
            set {
                this.messageTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public UserText AnnotationText {
            get {
                return this.annotationTextField;
            }
            set {
                this.annotationTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime IssueDate {
            get {
                return this.issueDateField;
            }
            set {
                this.issueDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public X509IssuerSerial Signer
        {
            get {
                return this.signerField;
            }
            set {
                this.signerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.Xml.XmlElement RequiredExtensions {
            get {
                return this.requiredExtensionsField;
            }
            set {
                this.requiredExtensionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.Xml.XmlElement NonCriticalExtensions {
            get {
                return this.nonCriticalExtensionsField;
            }
            set {
                this.nonCriticalExtensionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.smpte-ra.org/schemas/430-3/2006/ETM")]
    public partial class UserText {
        
        private string languageField;
        
        private string valueField;
        
        public UserText() {
            this.languageField = "en";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="language")]
        [System.ComponentModel.DefaultValueAttribute("en")]
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="AuthenticatedPrivateType", Namespace="http://www.smpte-ra.org/schemas/430-3/2006/ETM")]
    public partial class AuthenticatedPrivateType {
        
        private System.Xml.XmlElement[] encryptedKeyField;
        
        private System.Xml.XmlElement encryptedDataField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="EncryptedKey", Namespace="http://www.smpte-ra.org/schemas/430-3/2006/ETM", Order=0)]
        public System.Xml.XmlElement[] EncryptedKey {
            get {
                return this.encryptedKeyField;
            }
            set {
                this.encryptedKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="EncryptedData", Namespace="http://www.smpte-ra.org/schemas/430-3/2006/ETM", Order=1)]
        public System.Xml.XmlElement EncryptedData {
            get {
                return this.encryptedDataField;
            }
            set {
                this.encryptedDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "Id", Namespace = "http://www.smpte-ra.org/schemas/430-3/2006/ETM", DataType = "ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
}
